name: Add Label
on:
  workflow_call:
    inputs:
      issue:
        required: true
        type: string
      label:
        required: true
        type: string
jobs:
  add-label:
    runs-on: ubuntu-latest
    if: github.event.issue.user.login != 'renovate[bot]'
    steps:
      - name: Add label $LABEL
        run: gh issue edit "$NUMBER" --add-label "$LABEL"
        env:
          LABELS: ${{ inputs.label }}
          NUMBER: ${{ inputs.issue }}
          