name: Remove Label
inputs:
  issue:
    required: true
    type: string
  label:
    required: true
    type: string
  token:
    required: false
    type: string
runs:
  using: composite
  steps:
    - name: Remove label $LABEL
      run: |
        gh issue edit --repo $GH_REPO $NUMBER --remove-label $LABEL
      shell: bash
      env:
        LABEL: ${{ inputs.label }}
        NUMBER: ${{ inputs.issue }}
        GH_TOKEN: ${{ inputs.token }}
        