name: '🏠 Auto shutdown release form'
labels: 'release form'
description: Form to prevent aks-auto-shutdown on a certain env for application release

body:
  - type: input
    attributes:
      label: ">>Environment>>"
      description: |
        cluster environment
      placeholder: |
        environment
    validations:
      required: true
  - type: input
    attributes:
      label: ">>Start-Date>>"
      description: |
        Date for when the release will begin
      placeholder: |
        01/01/24
    validations:
      required: true
  - type: input
    attributes:
      label: ">>End-Date>>"
      description: |
        Date for when the release will end
      placeholder: |
        01/01/24
    validations:
      required: true
