name: '🏠 Auto shutdown release form'
labels: 'release form'
description: Form to prevent aks-auto-shutdown on a certain env for application release

body:
  - type: dropdown
    attributes:
      label: Business Area
      description: Business Area
      options:
        - CFT
        - SDS
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: cluster environment
      options:
        - sbox
        - test/perftest
        - ithc
        - demo
        - ptlsbox
        - preview
        - aat
    validations:
      required: true
  - type: input
    attributes:
      label: Start-Date
      description: |
        Date for when the release will begin
      placeholder: |
        01/01/2023
    validations:
      required: true
  - type: input
    attributes:
      label: End-Date
      description: |
        Date for when the release will end
      placeholder: |
        01/01/2023
    validations:
      required: true
