name: '🌍 Skip auto shutdown'
description: Request that an environment is not shutdown (automatically processed)
body:
- type: input
  attributes:
    label: Change or Jira reference
  validations:
    required: true

- type: dropdown
  id: download
  attributes:
    label: Business area
    options:
      - CFT
      - Cross-Cutting
  validations:
    required: true
    
- type: dropdown
  id: Environment
  attributes:
    label: Environment
    multiple: true
    options:
      - Sandbox
      - AAT / Staging
      - Preview / Dev
      - Test / Perftest
      - Demo
      - ITHC
  validations:
    required: true
      
- type: input
  id: Start_Date
  attributes:
    label: Skip shutdown start date
    description: "DD-MM-YYYY"
  validations:
    required: true
    
- type: input
  id: End_Date
  attributes:
    label: Skip shutdown end date
    description: "Defaults to start date. DD-MM-YYYY"
  validations:
    required: false
