name: Skip auto shutdown request
description: Skip auto shutdown request
body:    
- type: dropdown
  id: businessID
  attributes:
    label: businessLabel
    options:
      - cft
      - cross-cutting
  validations:
    required: true
    
- type: dropdown
  id: enviornments
  attributes:
    label: Environments
    multiple: true
    options:
      - Sandbox
      - AAT / Staging
      - Preview / Dev
      - Test / Perftest
      - Demo
      - ITHC
  validations:
    required: true
      
- type: input
  id: start_date_ID
  attributes:
    label: Skip shutdown start date label
    description: "DD-MM-YYYY"
  validations:
    required: true
    
- type: input
  id: end_date_ID
  attributes:
    label: Skip shutdown end date label
    description: "Defaults to current day. DD-MM-YYYY"
  validations:
    required: false
