name: Skip auto shutdown request
description: Skip auto shutdown request
body:
- type: input
  attributes:
    label: Why do you need the auto shutdown skipped?
  validations:
    required: true

- type: dropdown
  id: download
  attributes:
    label: Business area
    options:
      - cft
      - cross-cutting
  validations:
    required: true
    
- type: dropdown
  id: Enviornment
  attributes:
    label: Environment
    multiple: true
    options:
      - Sandbox
      - AAT / Staging
      - Preview / Dev
      - Test / Perftest
      - Demo
      - ITHC
  validations:
    required: true
      
- type: input
  id: Start_Date
  attributes:
    label: Skip shutdown start date
    description: "DD-MM-YYYY"
  validations:
    required: true
    
- type: input
  id: End_Date
  attributes:
    label: Skip shutdown end date
    description: "Defaults to current day. DD-MM-YYYY"
  validations:
    required: false
