name: Add Label
inputs:
  issue:
    required: true
    type: string
  label:
    required: true
    type: string
  token:
    required: false
    type: string
runs:
  using: composite
  steps:
    - name: test gh cli
      run: |
        echo "AUTHOR=$(gh issue view --repo endakelly/aks-auto-shutdown-releases 4 --json author | jq -r '.author.login')" >> $GITHUB_ENV
      shell: bash

    - name: test gh cli output
      run: |
        echo "author is $AUTHOR"
      shell: bash
      
    - name: Add label $LABEL
      run: gh issue edit --repo "$GH_REPO" "$NUMBER" --add-label "$LABEL"
      shell: bash
      env:
        LABELS: ${{ inputs.label }}
        NUMBER: ${{ inputs.issue }}
        GH_TOKEN: ${{ inputs.token }} 
        