name: Add Label
inputs:
  issue:
    required: true
    type: string
  label:
    required: true
    type: string
  token:
    required: false
    type: string
runs:
  using: composite
  steps:
    - name: Add label $LABEL
      run: |
        echo "Label is $LABEL"
        gh issue edit --repo $GH_REPO $NUMBER --add-label $LABEL
      shell: bash
      env:
        LABELS: ${{ inputs.label }}
        NUMBER: ${{ inputs.issue }}
        GH_TOKEN: ${{ inputs.token }}
        