name: Add Label
inputs:
  issue:
    required: true
    type: string
  label:
    required: true
    type: string
  repo:
    required: true
    type: string
runs:
  using: composite
  steps:
    - name: Add label $LABEL
      run: gh issue edit --repo "$REPO" "$NUMBER" --add-label "$LABEL"
      shell: bash
      env:
        LABELS: ${{ inputs.label }}
        NUMBER: ${{ inputs.issue }}
        REPO: ${{ inputs.repo }}        
        