name: Add Label
on:
  workflow_call:
    inputs:
      issue:
        required: true
        type: string
      label:
        required: true
        type: string
jobs:
  add-label:
    runs-on: ubuntu-latest
    if: github.event.issue.user.login != 'renovate[bot]'
    steps:
      - name: Add label ${{ inputs.label }}
        run: gh issue edit "${{ inputs.issue }}" --add-label "${{ inputs.label }}"
        env:
          LABELS: ${{ inputs.label }}