name: Housekeeping Shutdown form
run-name: Housekeeping json file
on:
  schedule:
    - cron:  '00 18 * * *'
  workflow_dispatch:
jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
     
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install python-dateutil
        run: |
          pip3 install python-dateutil
          
      - name: Delete old entries
        continue-on-error: true
        run: |
          python housekeeping.py

      - name: Commit / Merge
        if: env.JSON_FILE_EXISTS == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b PR-${{ github.run_id }}
          echo "=============="
          git add .
          git status
          git commit -m "parseissues" --allow-empty
          git push --set-upstream origin PR-${{ github.run_id }}
          gh pr create -f  -t ${{ github.run_id }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"  
          
          
      - name: Install jq tool
        if: env.JSON_FILE_EXISTS == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install jq
          
      - name: get PR details 
        if: env.JSON_FILE_EXISTS == 'true'
        uses: octokit/request-action@v2.x
        id: get_pr_number
        with:
          route: GET /repos/mokainos/actions/pulls
          owner: octokit
          repo: request-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
      - name: Set env
        if: env.JSON_FILE_EXISTS == 'true'
        run: | 
            echo PR_NUM=$(echo '${{ steps.get_pr_number.outputs.data }}' | jq -r '.[] | select(.title | contains("${{ github.run_id }}"))| .number' ) >>   $GITHUB_ENV
     
      - name: echo_prnum
        if: env.JSON_FILE_EXISTS == 'true'
        run: |
          echo PR_NUM ${{ env.PR_NUM }}
                
         
      - name: approve
        if: env.JSON_FILE_EXISTS == 'true'
        run: |
          gh pr review ${{ env.PR_NUM }} --approve
        env:
          GITHUB_TOKEN: "${{ secrets.MOKAINOS }}"
          
      - name: merge
        if: env.JSON_FILE_EXISTS == 'true'
        run: |
          gh pr merge ${{ env.PR_NUM }} --admin -m
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
