name: Auto Parse github form - test
run-name: ${{ github.actor }} - issue:${{ github.event.issue.number }}
on:
  issues:
    types:
      - opened
      - edited
  workflow_dispatch:
jobs:
  parse:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Parse issue
        id: parse_issue
        uses: onmax/issue-form-parser@v1.4
        with:
          issue_number: ${{ github.event.issue.number }}
      
      - name: Show parsed payload data
        run: |
          # Using the character `'` to prevent all characters enclosed within
          # them from being treated as special characters (e.g. $ or `)
          echo '${{ steps.parse_issue.outputs.payload }}'
          echo NEW_DATA='${{ steps.parse_issue.outputs.payload }}' >> $GITHUB_ENV
          echo GITHUB_REPO='${{ github.repository }}' >> $GITHUB_ENV
          echo ISSUE_NUMBER='${{ github.event.issue.number }}' >> $GITHUB_ENV

      - name: echo GitHub Env
        run: |
          echo $GITHUB_ENV
          env

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install python-dateutil
        run: |
          pip3 install python-dateutil

      - name: Delete old entries
        continue-on-error: true
        run: |
          python housekeeping.py
          
      - name: process form data
        continue-on-error: true
        run: |
          python file_handling.py

      - name: echo GitHub Env
        run: |
          echo $GITHUB_ENV
          env

      - name: Create Issue Comment
        uses: peter-evans/create-or-update-comment@v3.0.2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Output:
            ${{ env.ISSUE_COMMENT }}

      - name: Commit to master
        if: env.PROCESS_SUCCESS == 'true'
        run: |
          git config user.name hmcts-platform-operations
          git config user.email github-platform-operations@hmcts.net
          git add .
          git commit -m "parseissues"
          git push --force --set-upstream origin master

        env:
          GITHUB_TOKEN: "${{ secrets.PLATFORM_USER_TOKEN }}"
    
      - name: Close Issue
        if: env.PROCESS_SUCCESS == 'true'
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Auto-closing issues