name: Close inactive issues
on:
  workflow_dispatch:
  schedule:
    - cron: "00 08 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 0
          days-before-issue-close: 0
          stale-issue-label: "stale"
          close-issue-message: "This issue was closed because it has been inactive for 14 days."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
